const MOVIES = {
  LOAD: "LOAD",
  LOAD_SUCCESS: "SUCCESS",
  LOAD_FAIL: "FAIL",

  GENRE_LOAD: "GENRELOAD",
  GENRE_SUCCESS: "GENRESUCCESS",

  REC_LOAD: "RECLOAD",
  REC_LOAD_SUCCESS: "RECLOADSUCCESS",

  SEARCH_LOAD: "SLOAD",
  SEARCH_SUCCESS: "SSUCCESS",

  GETAMOVIE: "MLOAD",
  SETAMOVIE: "MSUCCESS",
  AMOVIE_FAIL: "MFAIL",

  CLEAR: "CLEAR_STATE"
};
export { MOVIES };
