const MOVIES = {
  LOAD: "LOAD",
  LOAD_SUCCESS: "SUCCESS",
  LOAD_FAIL: "FAIL",
  GENRE: "GENRE",
  REC_LOAD: "RECLOAD",
  REC_LOAD_SUCCESS: "RECLOADSUCCESS",
  SEARCH_LOAD: "SLOAD",
  SEARCH_SUCCESS: "SSUCCESS"
};
export { MOVIES };
